(function(global){
'use strict';
const NS=global.MMLCaseModules=global.MMLCaseModules||{};
function text(value){return value==null?'':String(value).trim()}
function arr(value){if(Array.isArray(value))return value.filter(Boolean);if(!value)return[];return String(value).split(/[,\n]/).map(v=>v.trim()).filter(Boolean)}
function first(obj,keys){for(const key of keys){const value=obj&&obj[key];if(value!==undefined&&value!==null&&String(value).trim()!=='')return value}return''}
function slug(value){return text(value).toLowerCase().replace(/\s+/g,'-').replace(/[^0-9a-z가-힣_-]/g,'').slice(0,80)}
function clientKey(source){const email=text(first(source,['email','userEmail','clientEmail'])).toLowerCase();if(email)return`email:${email}`;const phone=text(first(source,['phone','mobile','contact','tel'])).replace(/\D/g,'');if(phone)return`phone:${phone}`;const memberId=text(first(source,['memberId','userId','clientId']));if(memberId)return`member:${memberId}`;const name=text(first(source,['name','clientName','userName','applicantName']));return name?`name:${slug(name)}`:'anonymous'}
function sourceId(source,prefix){return text(first(source,['id','reservationId','requestId','reportId','uploadId']))||`${prefix}-${Date.now()}-${Math.random().toString(36).slice(2,8)}`}
function caseId(source){const explicit=text(first(source,['caseId','clinicalCaseId']));if(explicit)return explicit;const reservation=text(first(source,['reservationId','id']));if(reservation)return`case-${slug(reservation)}`;return`case-${slug(clientKey(source))}`}
function mapReservation(row){return{id:sourceId(row,'reservation'),date:text(first(row,['date','reservationDate','scheduledDate'])),time:text(first(row,['time','reservationTime','scheduledTime'])),program:text(first(row,['program','programName','serviceName'])),method:text(first(row,['method','counselingMethod','consultationType'])),status:text(first(row,['status','progressStatus']))||'예약접수',tests:arr(first(row,['tests','testNames','selectedTests','assessmentNames'])),rawId:text(first(row,['id','reservationId']))}}
function mapAssessment(row){return{id:sourceId(row,'assessment'),testName:text(first(row,['testName','assessmentName','name','type'])),status:text(first(row,['status','analysisStatus']))||'결과등록',fileName:text(first(row,['fileName','name'])),uploadedAt:text(first(row,['uploadedAt','createdAt','date'])),summary:text(first(row,['summary','analysis','resultSummary'])),rawId:text(first(row,['id','uploadId']))}}
function mapReport(row){return{id:sourceId(row,'report'),reportType:text(first(row,['reportType','type','kind']))||'individual',testName:text(first(row,['testName','assessmentName'])),status:text(first(row,['status','approvalStatus']))||'draft',approved:Boolean(first(row,['approved','isApproved']))||text(first(row,['status','approvalStatus'])).includes('승인'),updatedAt:text(first(row,['updatedAt','savedAt','createdAt'])),rawId:text(first(row,['id','reportId']))}}
function mapCounseling(row){return{id:sourceId(row,'counseling'),session:Number(first(row,['session','sessionNo','round']))||null,date:text(first(row,['date','sessionDate','createdAt'])),method:text(first(row,['method','counselingMethod'])),status:text(first(row,['status']))||'기록',summary:text(first(row,['summary','content','sessionSummary'])),rawId:text(first(row,['id','recordId']))}}
function baseCase(source){return{id:caseId(source),clientKey:clientKey(source),client:{name:text(first(source,['name','clientName','userName','applicantName'])),email:text(first(source,['email','userEmail','clientEmail'])),phone:text(first(source,['phone','mobile','contact','tel'])),memberId:text(first(source,['memberId','userId','clientId']))},status:'REQUESTED',lifecycleState:'REQUESTED',lifecycleHistory:[],reservations:[],assessments:[],reports:[],counseling:[],meta:{schemaVersion:1,source:'legacy-local-storage'}}}
NS.caseMapper=Object.freeze({clientKey,caseId,baseCase,mapReservation,mapAssessment,mapReport,mapCounseling});
})(window);
