(function(global){
'use strict';
const NS=global.MMLCaseModules=global.MMLCaseModules||{};
const STATE=Object.freeze({
 REQUESTED:'REQUESTED',
 APPROVED:'APPROVED',
 PAID:'PAID',
 ASSESSMENT_SENT:'ASSESSMENT_SENT',
 ASSESSMENT_COMPLETED:'ASSESSMENT_COMPLETED',
 AI_ANALYZED:'AI_ANALYZED',
 INDIVIDUAL_REPORT_CREATED:'INDIVIDUAL_REPORT_CREATED',
 INDIVIDUAL_REPORT_APPROVED:'INDIVIDUAL_REPORT_APPROVED',
 COMPREHENSIVE_REPORT_CREATED:'COMPREHENSIVE_REPORT_CREATED',
 COMPREHENSIVE_REPORT_APPROVED:'COMPREHENSIVE_REPORT_APPROVED',
 AI_COUNSELING_AVAILABLE:'AI_COUNSELING_AVAILABLE',
 COUNSELING_COMPLETED:'COUNSELING_COMPLETED',
 CLOSED:'CLOSED'
});
const ORDER=Object.freeze([
 STATE.REQUESTED,STATE.APPROVED,STATE.PAID,STATE.ASSESSMENT_SENT,
 STATE.ASSESSMENT_COMPLETED,STATE.AI_ANALYZED,STATE.INDIVIDUAL_REPORT_CREATED,
 STATE.INDIVIDUAL_REPORT_APPROVED,STATE.COMPREHENSIVE_REPORT_CREATED,
 STATE.COMPREHENSIVE_REPORT_APPROVED,STATE.AI_COUNSELING_AVAILABLE,
 STATE.COUNSELING_COMPLETED,STATE.CLOSED
]);
const LABELS=Object.freeze({
 [STATE.REQUESTED]:'예약 신청', [STATE.APPROVED]:'예약 승인', [STATE.PAID]:'결제 완료',
 [STATE.ASSESSMENT_SENT]:'검사 발송', [STATE.ASSESSMENT_COMPLETED]:'검사 완료',
 [STATE.AI_ANALYZED]:'AI 분석 완료', [STATE.INDIVIDUAL_REPORT_CREATED]:'개별보고서 생성',
 [STATE.INDIVIDUAL_REPORT_APPROVED]:'개별보고서 승인',
 [STATE.COMPREHENSIVE_REPORT_CREATED]:'종합보고서 생성',
 [STATE.COMPREHENSIVE_REPORT_APPROVED]:'종합보고서 승인',
 [STATE.AI_COUNSELING_AVAILABLE]:'AI 상담 가능', [STATE.COUNSELING_COMPLETED]:'상담 완료',
 [STATE.CLOSED]:'종결'
});
function normalize(value){const raw=String(value||'').trim().toUpperCase();return ORDER.includes(raw)?raw:STATE.REQUESTED}
function rank(value){return ORDER.indexOf(normalize(value))}
function label(value){return LABELS[normalize(value)]||LABELS[STATE.REQUESTED]}
function atLeast(value,target){return rank(value)>=rank(target)}
NS.caseState=Object.freeze({STATE,ORDER,LABELS,normalize,rank,label,atLeast});
})(window);
